# Generated by Django 5.1.1 on 2025-02-01 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reveiwrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReveiwRating',
            new_name='ReviewRating',
        ),
    ]
