# Generated by Django 5.1.1 on 2025-01-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
