# Generated by Django 5.1.1 on 2025-01-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_user_alter_orders_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variation',
            new_name='variations',
        ),
    ]
